# -*- coding: utf-8 -*-
"""Copy of Customer Segmentation Using K-Means Clustring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUDT6MSR70hqfykp4o5QAAMUourdnTyz
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

#loding the data
customer_data = pd.read_csv('/content/Mall_Customers.csv')

#frist 5 row of the data frame
customer_data.head()

#total  numbers fo row and colums in the data frame
customer_data.shape

#information about the data set
customer_data.info()

#checking for the missing values
customer_data.isnull().sum()

#Annual Income & Spending Score
x = customer_data.iloc[:,[3,4]].values

#finding WCSS values for differnt number of clusters
wcss = []

for i in range(1,11):
  k_means = KMeans(n_clusters=i,init='k-means++',random_state=42)
  k_means.fit(x)

  wcss.append(k_means.inertia_)

#plot an elbow graph
sns.set()
plt.plot(range(1,11),wcss)
plt.title('The Elbow Point Graph')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')

#traning the module K-Means

kmeans  = KMeans(n_clusters=5, init='k-means++',random_state=0)

#return lable for each data poins based on their clusters
y=kmeans.fit_predict(x)

print(y)

#plotting all the cluster and there centroids
plt.figure(figsize=(8,8))
plt.scatter(x[y==0,0],x[y==0,1],s=50,c='green',label='Cluster 1')
plt.scatter(x[y==1,0],x[y==1,1],s=50,c='blue',label='Cluster 2')
plt.scatter(x[y==2,0],x[y==2,1],s=50,c='yellow',label='Cluster 3')
plt.scatter(x[y==3,0],x[y==3,1],s=50,c='orange',label='Cluster 4')
plt.scatter(x[y==4,0],x[y==4,1],s=50,c='red',label='Cluster 5')

#plot the centroids
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=100,c='black',label='Centroids')

plt.title('Customer Groups')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')

